### ISSUE TITLE
Check compatibility with overcommit

### ISSUE THREAD

**Issue by jzaefferer** [jzaefferer/commitplease#72]
See https://github.com/brigade/overcommit

Sounds similar to husky.

**Comment by lencioni** [comment]
Relevant overcommit issue: https://github.com/brigade/overcommit/issues/405

**Comment by all3fox** [comment]
First impressions on a project with hooks set up (jQuery Core, actually):

```
gem install overcommit
overcommit --install
overcommit --sign
```

at this point overcommit backs up all existing hooks. The two hooks from husky that jQuery uses (precommit and commitmsg) are moved to `.git/hooks/old-hooks` and replaced as symbolic links to a ruby script `.git/hooks/overcommit-hook`. So, overcommit takes full control over all the preexisting hooks.

A very interesting command is `overcommit --list`. If we are talking about integration, then we should be looking at `CommitMsg` hook of overcommit. By the looks of it, none of the default checks contradict the checks performed by commitplease, so we just need to be called from there.

Ok, the way to get called by `overcommit` is to configure its `.overcommit.yml`. I have tried the following:

```
CommitMsg:
  commitplease:
    enabled: true
    command: ['node node_modules/commitplease']
```

That fails with:

```
Hook must specify a `required_executable` or `command` that is tracked by git (i.e. is a path relative to the root of the repository) so that it can be signed
```

I am investigating further

**Comment by all3fox** [comment]
I have tried several combinations of setting the `.overcommit.yml`, unsuccessfully yet. Primarily used brigade/overcommit#338 for info, here is what I have tried so far:

```
CommitMsg:
  commitplease:
    enabled: true
    required_executable: 'node'
    command: ['node', './node_modules/.bin/commitplease']
```
Since jQuery Core also has a dedicated script in its `package.json`, I have tried it (no luck):
```
CommitMsg:
  commitplease:
    enabled: true
    required_executable: 'npm'
    command: ['npm', 'run-script', 'commitmsg']
```

Then I came across a very nice [file in overcommit](https://github.com/brigade/overcommit/blob/78ad621267b08e6f04b0cd97ae6bec9a876451a0/config/default.yml#L538) that shows how other npm modules are supported. It looks like the proper way is to support global install.

`npm install -g commitplease` results in a long list of "Module is inside a symlinked module" warnings for me and a "command not found: commitplease" once I try to run commitplease.

@jzaefferer do you think we should:
 1. fix/find a way to support `npm install -g commitplease`? It looks like all available-by-default overcommit scripts that come from javascript world do that.
 2. just keep trying to get overcommit to run a local install of commitplease via `.overcommit.yml`?

@lencioni do you perhaps see any obvious thing that I am doing wrong?

**Comment by lencioni** [comment]
We typically set up the overcommit hooks to be able to run globally by default. People in their own projects can override the required_executable to be the local version if they happen to be using npm and have it in their devDependencies. For example, a project's .overcomm.yml file might include the following configuration for eslint:

```yaml
EsLint:
    enabled: true
    flags: ['--ext=.js,.jsx', '--format=compact']
    required_executable: './node_modules/.bin/eslint'
    include:
      - '**/*.js'
      - '**/*.jsx'
```

Borrowing from the ESLint default config, I think this might make sense for commitplease:

```yaml
  Commitplease:
    enabled: false
    description: 'Analyze with Commitplease'
    required_executable: 'commitplease'
    install_command: 'npm install -g commitplease'
```

And then allow folks to specify the local version if they want, when they enable it, like this:

```yaml
CommitPlease:
    enabled: true
    required_executable: './node_modules/.bin/commitplease'
```

Of course, you would need to make commitplease able to be installed globally for this setup to work. If you don't want to do that, you could probably roll with something like this for the default:

```yaml
  Commitplease:
    enabled: false
    description: 'Analyze with Commitplease'
    required_executable: './node_modules/.bin/commitplease'
    install_command: 'npm install --save-dev commitplease'
```

I hope this helps. Let me know if you have any more questions.

**Comment by all3fox** [comment]
@lencioni thank you! My issue appears to have been [security-related][1] and here is what worked for me:

Create a project and install the two packages: 

```
mkdir test-project && cd test-project && npm init --yes && git init
npm i commitplease --save-dev
overcommit --install
overcommit --sign
```

At this point, I have to begin the security dance [remember these two lines for later]:

```
git add ./node_modules/.bin/commitplease
git commit -m "Add commitplease to source control to fit overcommit security ways"
```

Now I configure `.overcommit.yml` to contain the suggested lines: 

```
  CommitMsg:
    Commitplease:
      enabled: true
      description: 'Analyze with Commitplease'
      required_executable: './node_modules/.bin/commitplease'
      install_command: 'npm install --save-dev commitplease'
```

And continue the security dance:

```
overcommit --sign commit-msg
```

And at this point it starts to work! Thanks!

#### Usability problem:

It does not look like I can skip the "add commitplease hook into git" lines that I have marked above. If I just skip straight into configuring `.overcommit.yml`, it will not install commitplease automatically even though there is an `install_command` setting. And it took me quite a while to realize that overcommit actually wants me to add a hook into source control.

And since I must add the hook to source control, I have to have it pre-installed before I configure overcommit. So, overcommit does not automatically install the missing hooks for me.

Am I doing something wrong?

[1]: https://github.com/brigade/overcommit/blob/master/README.md#security
